### ISSUE TITLE
Plugin not working with Piwik 3.0

### ISSUE THREAD

**Issue by Glisse1** [diabl0/piwik-geoip2#3]
Hello, already created [this issue](https://github.com/piwik/piwik/issues/11034) in piwik branch

**Comment by slawa-dev** [comment]
Can confirm this plugin is currently not working! Hope this gets fixed as this plugin looks very promising.

Can @diabl0 have a look at the ticket in Piwik? https://github.com/piwik/piwik/issues/11034

Currently this geoip2 plugin is not used when tracking, even though it is working and selected in the settings menu.

Need to figure out if this issue is with Piwik or this Plugin.

**Note: When testing make sure that the result of geoip2 is NOT from default geoip provider (aka your browser language setting). So better use an IP (Proxy or VPN) of a country that is different than your preferred language in browser.**

@Glisse1 Can you rename this issue to something like "Plugin not working with Piwik 3.0"

**Comment by diabl0** [comment]
@Glisse1 https://github.com/piwik/piwik/issues/11034#issuecomment-269077262

**Comment by Glisse1** [comment]
This useful plugin is still 0 % working :(

**Comment by diabl0** [comment]
@Glisse1 I'm aware of that, but due to my tight schedule I haven't time to investigate it properly. 

For some reason despite having GeoIP2 plugin LocationProvider selected Piwik isn't calling it and using data from browser language to detect visitor country. 
I'm quiet sure it's related with changes within Piwik itself as it was working with earlier version, but will need to debug it throughly and find solution.

I have scheduled Piwik project later this month and then I will take care with this issue.

**Comment by Glisse1** [comment]
Thank you! 

I completely understand, there is no pressure on you. Everybody has their priorities and regardless when you will consider looking into this, we appreciate... It`s just that for instance i have a piwik chat plugin installed for like 2 years that  never worked. Never. Not for a single minute :)

I was just afraid of the same thing happening with this plugin, because i find this geoip2 much much more useful than the chat one (which also have tens of working alternatives outside piwik, unlike geolocation)

**Comment by depth42** [comment]
I would also greatly appreciate a fix for this great plug-in. 
I found out, that the current plugin works when re-calculating the country for old visits via the console like described here: https://piwik.org/faq/how-to/faq_167/

**Comment by iprok** [comment]
I fully confirm the issue. Plugin is fully unusable. Only shows correct information in Geolocation Settings but don't give info to piwik. @diabl0, have you plans to fix this? May be we can sponsor you someway?

**Comment by diabl0** [comment]
Fixed. 

Thanks for @ahaenggli for idea - i was trying with events to force piwik tracker to load plugin, and after finish I stumbled upon his fork.
